import './globals.css'
import '../styles/output.css'

import 'my-react-component/dist/style.css'

import ResponsiveWindow from '@/layout/ResponsiveWindow'
import Navbar from '@/components/Navbar'
import { StoreProviders, ThemeProviders } from '@/providers'
import Modal from '@/components/modal'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StoreProviders>
          <ThemeProviders>
            <Navbar />
            <ResponsiveWindow>{children}</ResponsiveWindow>
            <Modal />
          </ThemeProviders>
        </StoreProviders>
      </body>
    </html>
  )
}
